spring:
  mvc:
    cors:
      enabled: true
      mappings:
        "/**":
          allowed-origins: "http://localhost:5173"  # The frontend URL
          allowed-methods: "GET, POST, PUT, DELETE"  # Allowed HTTP methods
          allowed-headers: "*"  # Allowed headers
          allow-credentials: true  # Allow credentials like cookies or HTTP authentication
